version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:4.18.1
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "5900:5900"  # VNC порт
    shm_size: 2g
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox:4.18.1
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "5901:5900"  # VNC порт
    shm_size: 2g
    networks:
      - selenium-grid

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    volumes:
      - ./:/app
      - ./test-results:/app/test-results
    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge 